version: "3.8"

services:
  restream:
    build: .
    ports:
      - "8080:8080"
      - "1935:1935"
    environment:
      - SOURCE_URL=https://storage.filebin.net/filebin/3158b42772e5451996ca831a349ede8387009062a200ccbc98b4eb6f580fad25?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GK352fd2505074fc9dde7fd2cb%2F20260522%2Fhel1-dc4%2Fs3%2Faws4_request&X-Amz-Date=20260522T214236Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&response-cache-control=max-age%3D900&response-content-disposition=inline%3B%20filename%3D%22playlist.m3u%22&response-content-type=application%2Fvnd.apple.mpegurl&x-id=GetObject&X-Amz-Signature=27e2c5a954f6e779c472bcd5eb8bbc2d767a8bb43e0ae4389cef5ce28a0da7a0
      - PORT=8080
      - NGINX_RTMP_PORT=1935
      - HLS_FRAGMENT=10
      - HLS_PLIST_LENGTH=15
      - MAX_CONCURRENT=100
      - CHANNEL_REFRESH=60
    volumes:
      - ./logs:/var/log
      - hls-data:/tmp/hls
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  hls-data:
