# ============================================================
# Logrotate – HLS Restreamer v2.1.0
# ============================================================
/root/logs/*.log {
    daily
    rotate 3
    compress
    delaycompress
    missingok
    notifempty
    size 10M
    maxsize 10M
    copytruncate
    su root root
}
